<?php
error_reporting(E_ALL);define('ABSPATH','/tmp/');define('ARRAY_A','ARRAY_A');
$GLOBALS['opts']=[];class WP_Error{private $c,$m;function __construct($c='',$m=''){$this->c=$c;$this->m=$m;}function get_error_code(){return $this->c;}function get_error_message(){return $this->m;}}function is_wp_error($x){return $x instanceof WP_Error;}function absint($v){return abs((int)$v);}function sanitize_key($v){return preg_replace('/[^a-z0-9_\-]/','',strtolower((string)$v));}function sanitize_text_field($v){return trim(strip_tags((string)$v));}function wp_json_encode($v,$o=0){return json_encode($v,$o);}function maybe_serialize($v){return serialize($v);}function get_option($k,$d=[]){return array_key_exists($k,$GLOBALS['opts'])?$GLOBALS['opts'][$k]:$d;}function update_option($k,$v,$a=false){$GLOBALS['opts'][$k]=$v;return true;}function wp_cache_delete($a,$b=''){return true;}function wp_next_scheduled($h){return false;}function wp_schedule_single_event($t,$h){return true;}function wp_unschedule_event($t,$h){return true;}
$root=getenv('PPAR_TEST_PLUGIN_DIR');if(!$root)exit(2);require $root.'/includes/trait-ppar-ebay-run.php';
class H{use PPAR_Ebay_Run_Trait;
 const OPTION_EBAY_RUN_STATE='run',OPTION_EBAY_PUBLIC_CHECKPOINT='checkpoint',OPTION_EBAY_RUN_HISTORY='history',OPTION_EBAY_SYNC_JOB='sync',OPTION_EBAY_REFRESH_JOB='refresh',OPTION_EBAY_SELECTION_STATE='selection',OPTION_EBAY_MAINTENANCE_STATE='maintenance';
 const EBAY_RUNTIME_BUILD='6.51-cleanup-failclosed-test',EBAY_CONTENT_POLICY_VERSION='5',EBAY_PRIVATE_CLASSIFIER_VERSION='4',EBAY_BUSINESS_CLASSIFIER_VERSION='5',EBAY_PROGRESS_CONTRACT_VERSION='3.0',EBAY_WORKER_HOOK='worker';
 public $ebay_canonical_worker_active=false,$ebay_run_settings_override=null;
 private function output_local_portal_key(){return'local';}private function ebay_settings(){return['enabled'=>1,'business_enabled'=>1,'private_enabled'=>1];}private function ebay_normalize_settings($s,$k=true){return is_array($s)?$s:[];}private function ebay_catalog_rules(){return[];}
 private function ebay_selection_prune_business_batch($settings,&$state,$limit=20,$commit_public=false,$terminal_transition=true){$state['status']='failed';$state['phase']='failed';$state['failure_reason']='storage_unavailable_prune';return 0;}
 private function ebay_selection_apply_private_post_batch($settings,&$state,$limit=50,$commit_public=false,$terminal_transition=true){$state['status']='failed';$state['phase']='private_posts';$state['error']='storage unavailable';return 0;}
 public function seed($route){$GLOBALS['opts']=[];$GLOBALS['opts']['checkpoint']=['checkpoint_id'=>'safe-before','business_campaign_ids'=>[11],'private_listing_ids'=>[22]];$GLOBALS['opts']['run']=['schema'=>'1.0','build'=>self::EBAY_RUNTIME_BUILD,'run_uuid'=>'cleanup-run','status'=>'running','phase'=>'checkpoint_cleanup_'.$route,'started_at'=>1,'updated_at'=>1,'finished_at'=>0,'owner'=>'','lease_expires_at'=>0,'no_progress_count'=>0,'progress_seq'=>20,'config_snapshot'=>['seller_routes'=>['business'=>1,'private'=>1],'settings'=>['enabled'=>1,'business_enabled'=>1,'private_enabled'=>1]],'checkpoint_id'=>'safe-before','checkpoint_verified_manifest'=>['business'=>['status'=>'pass'],'private'=>['status'=>'pass']],'checkpoint_cleanup_selection'=>['status'=>'complete','phase'=>'complete'],'phase_state'=>[],'coverage'=>[],'gapfill'=>[],'errors'=>[]];}
 public function cleanup($route){$m=new ReflectionMethod($this,'ebay_run_tick_checkpoint_cleanup');$m->setAccessible(true);$m->invoke($this,$this->ebay_run_load(),['business_enabled'=>1,'private_enabled'=>1],$route);return $this->ebay_run_load();}public function checkpoint(){return $this->ebay_public_checkpoint_load();}
}
$f=0;$n=0;function ck($v,$m){global$f,$n;$n++;echo($v?'PASS ':'FAIL ').$m."\n";if(!$v)$f++;}
foreach(['business','private'] as $route){$h=new H();$h->seed($route);$before=$h->checkpoint();$r=$h->cleanup($route);$code='checkpoint_'.$route.'_cleanup_failed';ck(($r['status']??'')==='failed'&&($r['error_code']??'')===$code,$route.' cleanup failure is terminal and route-specific');ck(absint($r['no_progress_count']??0)===0,$route.' cleanup failure is not misreported as no-progress');ck(($h->checkpoint()['checkpoint_id']??'')===($before['checkpoint_id']??''),$route.' cleanup failure preserves the verified public checkpoint');$last=end($r['errors']);ck(($last['details']['cleanup_reason']??'')!=='',$route.' cleanup failure persists concrete cleanup reason');}
echo "ASSERTIONS=$n FAIL=$f\n";exit($f?1:0);
