<?php
error_reporting(E_ALL);define('ABSPATH','/tmp/');define('ARRAY_A','ARRAY_A');
$GLOBALS['opts']=[];class WP_Error{private $c,$m;function __construct($c='',$m=''){$this->c=$c;$this->m=$m;}function get_error_code(){return $this->c;}function get_error_message(){return $this->m;}}function is_wp_error($x){return $x instanceof WP_Error;}function absint($v){return abs((int)$v);}function sanitize_key($v){return preg_replace('/[^a-z0-9_\-]/','',strtolower((string)$v));}function sanitize_text_field($v){return trim(strip_tags((string)$v));}function wp_json_encode($v,$o=0){return json_encode($v,$o);}function get_option($k,$d=[]){return array_key_exists($k,$GLOBALS['opts'])?$GLOBALS['opts'][$k]:$d;}function update_option($k,$v,$a=false){$GLOBALS['opts'][$k]=$v;return true;}function wp_next_scheduled($h){return false;}function wp_schedule_single_event($t,$h){return true;}function wp_clear_scheduled_hook($h){return 1;}
$root=getenv('PPAR_TEST_PLUGIN_DIR');if(!$root){exit(2);}require $root.'/includes/trait-ppar-ebay-run.php';
class H{use PPAR_Ebay_Run_Trait;const OPTION_EBAY_RUN_STATE='run',OPTION_EBAY_SYNC_JOB='sync',OPTION_EBAY_REFRESH_JOB='refresh',OPTION_EBAY_SELECTION_STATE='selection',OPTION_EBAY_MAINTENANCE_STATE='maintenance',EBAY_RUNTIME_BUILD='6.42.0-live82311',EBAY_CONTENT_POLICY_VERSION='p',EBAY_PRIVATE_CLASSIFIER_VERSION='pc',EBAY_BUSINESS_CLASSIFIER_VERSION='bc',EBAY_WORKER_HOOK='w',EBAY_REFRESH_WORKER_HOOK='rw';public $ebay_canonical_worker_active=false,$ebay_run_settings_override=null,$missing=[];function __construct(){$ids=[];for($i=1;$i<=311;$i++)$ids[]=sprintf('concept-%03d',$i);$this->missing=array_slice($ids,82);}private function ebay_run_public_business_coverage(){return ['required'=>311,'covered'=>82,'missing'=>$this->missing,'counts'=>array_fill_keys(array_map(fn($i)=>sprintf('concept-%03d',$i),range(1,82)),1)];}public function seed(){$r=['schema'=>'1.0','build'=>self::EBAY_RUNTIME_BUILD,'run_uuid'=>'live-82-311','status'=>'running','phase'=>'coverage_verify','started_at'=>1,'updated_at'=>1,'finished_at'=>0,'owner'=>'','lease_expires_at'=>0,'worker_transport'=>'admin_ajax','resume_reason'=>'','no_progress_count'=>0,'progress_seq'=>10,'phase_state'=>[],'coverage'=>[],'gapfill'=>['attempts'=>0,'missing'=>[]],'errors'=>[]];update_option('run',$r,false);}public function coverage(){return $this->ebay_run_tick_coverage($this->ebay_run_load(),['business_enabled'=>1]);}public function run(){return $this->ebay_run_load();}}
$f=0;$n=0;function ck($v,$m){global$f,$n;$n++;echo($v?'PASS ':'FAIL ').$m."\n";if(!$v)$f++;}
$h=new H();$h->seed();$h->coverage();$r=$h->run();ck(($r['status']??'')==='running'&&($r['phase']??'')==='gapfill_discovery','82/311 live shape enters targeted gap-fill instead of terminal success');ck(count($r['gapfill']['missing']??[])===229,'exact 82/311 live shape persists exactly 229 missing families');ck(($r['gapfill']['missing']??[])===$h->missing,'gap-fill list is exactly the 229 missing family identities');ck(($r['gapfill']['attempts']??0)===1,'82/311 shape schedules exactly one bounded gap-fill attempt');ck(($r['run_uuid']??'')==='live-82-311','gap-fill preserves the same canonical run_uuid');
$r['phase']='coverage_verify';
$r['phase_state']['selection']=['status'=>'complete','reason'=>'canonical_gapfill','selection_scope'=>'business','owner'=>'run:live-82-311','business_target_mode'=>'gapfill','business_target_concepts'=>$h->missing,'business_active'=>[]];
update_option('run',$r,false);$h->coverage();$r=$h->run();$ex=(array)($r['coverage']['exceptions']??[]);
ck(($r['status']??'')==='running'&&($r['phase']??'')==='public_verify'&&($r['coverage']['contract_status']??'')==='complete_with_safe_supply_gaps','remaining 229 become proven open safe supply gaps after one targeted gap-fill');
ck(count($ex)===229,'every remaining family receives an explicit open-gap entry');
$all=true;foreach($h->missing as$id){if(($ex[$id]['code']??'')!=='safe_supply_gap_open'||($ex[$id]['approved']??1)!==0||($ex[$id]['public']??1)!==0){$all=false;break;}}
ck($all,'all 229 gap entries stay non-approved and non-public');
ck(($r['gapfill']['attempts']??0)===1,'82/311 recovery never starts a second/global gap-fill');
ck(($r['run_uuid']??'')==='live-82-311','82/311 recovery preserves original run_uuid');
echo "ASSERTIONS=$n FAIL=$f\n";exit($f?1:0);
