<?php
if (!defined('ABSPATH')) { exit(2); }
$scenario=getenv('AFF_E2E_SCENARIO') ?: 'healthy';
$targets=array('reithelme'=>186,'reithandschuhe'=>187,'reitstiefel'=>188,'sicherheitswesten'=>189,'gerten'=>190,'sporen'=>191,'halfter-und-stricke-stallhalfter'=>174);
function e2e_clear_exact_for_slug($slug,$keep=0){$posts=get_posts(array('post_type'=>'ap_campaign','post_status'=>'any','numberposts'=>-1,'fields'=>'ids'));$kept=0;foreach($posts as $id){$c=get_post_meta($id,'ppar_campaign_data',true);if(!is_array($c)||empty($c['active'])||sanitize_key((string)($c['creative_type']??''))!=='product')continue;$keys=array_values((array)($c['automation_target_keys']??array()));$needle='page:'.$slug;if(!in_array($needle,$keys,true))continue;if($kept<$keep){$kept++;continue;}$c['automation_target_keys']=array_values(array_filter($keys,static fn($k)=>$k!==$needle));update_post_meta($id,'ppar_campaign_data',$c);}}
if($scenario==='idealo_only'||$scenario==='live_damage'){$s=get_option('ppar_network_idealo_v1',array());$s['enabled']=1;$s['output_mode']='idealo_only';$s['link_strategy']='products';$s['last_import_at']=time();update_option('ppar_network_idealo_v1',$s,false);}
if($scenario==='missing_exact_reithelme'||$scenario==='live_damage')e2e_clear_exact_for_slug('reithelme',0);
if($scenario==='one_exact_stallhalfter'||$scenario==='live_damage')e2e_clear_exact_for_slug('halfter-und-stricke-stallhalfter',1);
$results=array();$fail=0;
foreach($targets as $slug=>$id){$post=get_post($id);setup_postdata($post);$GLOBALS['post']=$post;$slots=array();for($i=1;$i<=3;$i++){$html=do_shortcode('[pp_affiliate_slot type="category_product_'.$i.'" intent="portal_context"]');$provider='none';if(stripos($html,'ebay.de')!==false)$provider='ebay';elseif(stripos($html,'idealo.')!==false)$provider='idealo';$title='';if(preg_match('/<strong class="ppar-banner-title">([^<]+)<\/strong>/u',$html,$m))$title=html_entity_decode($m[1],ENT_QUOTES|ENT_HTML5,'UTF-8');$real=strpos($html,'data-ppar-category-product-card="1"')!==false;$slots[]=array('slot'=>$i,'real'=>$real,'provider'=>$provider,'title'=>$title,'html_sha256'=>hash('sha256',$html));}$results[$slug]=$slots;}wp_reset_postdata();
echo 'SCENARIO='.$scenario."\n";foreach($results as $slug=>$slots)echo $slug.'='.wp_json_encode($slots,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)."\n";
if($scenario==='healthy'){foreach($results as $slug=>$slots){if(count(array_filter($slots,fn($x)=>$x['real']))<3){fwrite(STDERR,"FAIL_HEALTHY_CARD_COUNT:$slug\n");$fail++;}}$prov=array_column($results['reithelme'],'provider');if(!in_array('ebay',$prov,true)||!in_array('idealo',$prov,true)){fwrite(STDERR,"FAIL_HEALTHY_REITHELME_PROVIDER_MIX\n");$fail++;}}
if($scenario==='idealo_only'){foreach($results as $slug=>$slots)foreach($slots as $x)if($x['provider']==='ebay'){fwrite(STDERR,"FAIL_IDEALO_ONLY_EBAY_VISIBLE:$slug\n");$fail++;}}
if($scenario==='one_exact_stallhalfter'){$n=count(array_filter($results['halfter-und-stricke-stallhalfter'],fn($x)=>$x['real']));if($n!==1){fwrite(STDERR,"FAIL_STALLHALFTER_EXPECT_1_GOT_$n\n");$fail++;}}
if($scenario==='live_damage'){$prov=array_column($results['reithelme'],'provider');foreach($prov as $p)if($p==='ebay'){fwrite(STDERR,"FAIL_LIVE_DAMAGE_EBAY_VISIBLE\n");$fail++;}$n=count(array_filter($results['halfter-und-stricke-stallhalfter'],fn($x)=>$x['real']));if($n!==1){fwrite(STDERR,"FAIL_LIVE_DAMAGE_STALLHALFTER_EXPECT_1_GOT_$n\n");$fail++;}}
exit($fail?1:0);
