<?php
if(!defined('ABSPATH')){fwrite(STDERR,"WordPress required\n");exit(2);} 
$GLOBALS['v656_a']=0;$GLOBALS['v656_f']=0;
function v656ok($c,$n){$GLOBALS['v656_a']++; if(!$c){$GLOBALS['v656_f']++; echo "FAIL $n\n";} else echo "PASS $n\n";}
function v656call($o,$n,...$a){$m=new ReflectionMethod($o,$n);$m->setAccessible(true);return $m->invokeArgs($o,$a);} 
function v656data($r){return $r instanceof WP_REST_Response?$r->get_data():$r;}
$p=Pferdeportal_Affiliate_Router::instance();
require_once ABSPATH.'wp-admin/includes/plugin.php';
$pf=WP_PLUGIN_DIR.'/affiliate-portal-router/pferdeportal-affiliate-router.php';$pd=get_plugin_data($pf,false,false);
v656ok(($pd['Version']??'')==='6.56.0','wordpress_header_656');
v656ok(Pferdeportal_Affiliate_Router::VERSION==='6.56.0','class_version_656');
v656ok(Pferdeportal_Affiliate_Router::EBAY_RUNTIME_BUILD==='6.56.0-safe-gap-churn-revalidation-rootfix-20260827','runtime_656');
$read=(string)file_get_contents(WP_PLUGIN_DIR.'/affiliate-portal-router/readme.txt');
v656ok(substr_count($read,"\nStable tag: ")===1&&strpos($read,'Stable tag: 6.56.0')!==false,'stable_tag_656_unique');

do_action('rest_api_init');$routes=rest_get_server()->get_routes();$route='/'.Pferdeportal_Affiliate_Router::EBAY_EXTERNAL_TICK_REST_NAMESPACE.Pferdeportal_Affiliate_Router::EBAY_EXTERNAL_TICK_REST_ROUTE;
v656ok(isset($routes[$route]),'heartbeat_route_exists');
$url=v656call($p,'ebay_external_tick_url');v656ok(strpos($url,'key=')===false,'heartbeat_url_no_secret');
$settings=$p->ebay_settings_defaults();$settings['enabled']=true;$settings['private_enabled']=true;$settings['business_enabled']=true;$settings['inventory_refresh_enabled']=true;$settings['last_sync']=['finished_at'=>time()];$settings['last_refresh']=['finished_at'=>time()];update_option(Pferdeportal_Affiliate_Router::OPTION_NETWORK_EBAY,$settings,false);
$runKey=v656call($p,'ebay_run_option_key');$checkpointKey=v656call($p,'ebay_public_checkpoint_option_key');delete_option($runKey);delete_option(Pferdeportal_Affiliate_Router::OPTION_EBAY_EXTERNAL_TICK_RATE_LOCK);
$req=new WP_REST_Request('POST',$route);$idle=v656data($p->handle_ebay_external_tick($req));v656ok(($idle['status']??'')==='idle','heartbeat_idle_when_not_due');
$th=v656data($p->handle_ebay_external_tick($req));v656ok(($th['status']??'')==='throttled','heartbeat_45s_throttle');
$settings['last_sync']=['finished_at'=>time()-4*HOUR_IN_SECONDS];update_option(Pferdeportal_Affiliate_Router::OPTION_NETWORK_EBAY,$settings,false);v656ok(v656call($p,'ebay_external_tick_due_operation',$settings)==='sync','regular_sync_auto_due');
$settings['last_sync']=['finished_at'=>time()-30*MINUTE_IN_SECONDS];$settings['last_refresh']=['finished_at'=>time()-2*HOUR_IN_SECONDS];v656ok(v656call($p,'ebay_external_tick_due_operation',$settings)==='refresh','regular_refresh_auto_due');

$checkpoint=['schema'=>'1.0','status'=>'safe','checkpoint_id'=>'v656-safe-proof','business_campaign_ids'=>[11],'private_listing_ids'=>[21],'updated_at'=>time()];update_option($checkpointKey,$checkpoint,false);
$old=['schema'=>'1.0','build'=>'6.55.0-kiss-public-heartbeat-github-scheduler-20260823','run_uuid'=>'old-build','status'=>'running','phase'=>'reconcile_local','started_at'=>time()-30,'updated_at'=>time()-30,'phase_state'=>[],'errors'=>[],'checkpoint_base_id'=>'v656-safe-proof','owner'=>'','lease_expires_at'=>0];update_option($runKey,$old,false);$p->maybe_close_incompatible_ebay_run_for_checkpoint_restart();$closed=get_option($runKey,[]);
v656ok(($closed['status']??'')==='failed'&&($closed['error_code']??'')==='run_build_changed_restart_required','old_build_closes_fail_closed');v656ok(get_option($checkpointKey,[])===$checkpoint,'checkpoint_preserved_on_build_change');
update_option(Pferdeportal_Affiliate_Router::OPTION_EBAY_EXTERNAL_TICK_RATE_LOCK,time()-46,false);$fr=v656data($p->handle_ebay_external_tick($req));v656ok(($fr['status']??'')==='failed'&&absint($fr['restart_required']??0)===1,'failed_run_needs_explicit_restart');v656ok(!isset($fr['run_uuid'])&&!isset($fr['error_code']),'public_failure_response_minimal');

$required=v656call($p,'ebay_business_required_product_concept_ids');$required=array_values(array_unique(array_filter(array_map('sanitize_key',(array)$required))));sort($required,SORT_STRING);v656ok(count($required)===311,'real_manifest_311');
$target=array_slice($required,8);$current=array_slice($required,7);$uuid='v656-live-shape';
$sel=['status'=>'complete','phase'=>'complete','reason'=>'canonical_gapfill','selection_scope'=>'business','owner'=>'run:'.$uuid,'business_target_mode'=>'gapfill','business_target_concepts'=>$target,'business_active'=>[],'stats'=>['business'=>['errors'=>[]]]];
$run=['schema'=>'1.0','build'=>Pferdeportal_Affiliate_Router::EBAY_RUNTIME_BUILD,'run_uuid'=>$uuid,'status'=>'running','phase'=>'coverage_verify','started_at'=>time()-100,'updated_at'=>time()-1,'finished_at'=>0,'owner'=>'','lease_expires_at'=>0,'phase_state'=>['refresh'=>['sentinel'=>'KEEP_REFRESH'],'discovery'=>['status'=>'completed','sentinel'=>'OLD_DISCOVERY'],'selection'=>$sel],'coverage'=>[],'gapfill'=>['attempts'=>1,'missing'=>$target],'errors'=>[],'checkpoint_candidate'=>['business_campaign_ids'=>[11],'private_listing_ids'=>[21]],'checkpoint_base_id'=>'v656-safe-proof','source_sentinel'=>['keep'=>1],'progress_seq'=>10,'no_progress_count'=>0,'last_progress_at'=>time()-1];update_option($runKey,$run,false);
$coverage=['required'=>311,'covered'=>7,'missing'=>$current,'counts'=>[]];$oldContract=v656call($p,'ebay_run_business_safe_supply_gap_contract',$run,$coverage);v656ok(($oldContract['error_code']??'')==='business_safe_gap_new_missing_family','historic_guard_still_rejects_unproven_new_family');
$handled=v656call($p,'ebay_run_schedule_new_business_gap_revalidation',$run,$coverage,'coverage_verify');$after=get_option($runKey,[]);v656ok($handled===true&&($after['status']??'')==='running'&&($after['phase']??'')==='gapfill_discovery','live_churn_reenters_gapfill');v656ok(absint($after['gapfill']['attempts']??0)===2&&count((array)($after['gapfill']['missing']??[]))===304,'proof_scope_expands_once');v656ok(($after['gapfill']['discovery_missing']??[])===[$required[7]],'discovery_only_new_delta');v656ok(($after['phase_state']['refresh']['sentinel']??'')==='KEEP_REFRESH'&&($after['source_sentinel']['keep']??0)===1,'upstream_state_preserved');v656ok(($after['phase_state']['discovery']??null)===[]&&($after['phase_state']['selection']??null)===[],'derived_tail_reset_only');v656ok(get_option($checkpointKey,[])===$checkpoint,'public_checkpoint_preserved_during_revalidation');
$delta=v656call($p,'ebay_business_recovery_missing_concept_ids');sort($delta);v656ok($delta===[$required[7]],'real_discovery_scope_delta_only');
$after['phase']='gapfill_select';update_option($runKey,$after,false);$selectionSeed=['reason'=>'canonical_gapfill','owner'=>'run:'.$uuid];$scope=v656call($p,'ebay_selection_business_target_concepts',$selectionSeed);sort($scope);$expanded=$after['gapfill']['missing'];sort($expanded);v656ok($scope===$expanded&&count($scope)===304,'real_selector_owns_full_expanded_scope');
$after['phase']='coverage_verify';$after['phase_state']['selection']=['status'=>'complete','reason'=>'canonical_gapfill','selection_scope'=>'business','owner'=>'run:'.$uuid,'business_target_mode'=>'gapfill','business_target_concepts'=>$expanded,'business_active'=>[]];update_option($runKey,$after,false);$pass=v656call($p,'ebay_run_business_safe_supply_gap_contract',$after,$coverage);v656ok(($pass['status']??'')==='pass'&&absint($pass['coverage']['open_gap_count']??0)===304,'unchanged_safe_gap_contract_passes_after_full_proof');
$bad=$after;$bad['phase_state']['selection']['business_active']=['proof'=>['concept'=>$required[7],'rank'=>1]];$inv=v656call($p,'ebay_run_business_safe_supply_gap_contract',$bad,$coverage);v656ok(($inv['error_code']??'')==='business_gapfill_public_invariant_failed','selected_not_public_still_hard');
$cov2=['required'=>311,'covered'=>6,'missing'=>array_slice($required,6),'counts'=>[]];update_option($runKey,$after,false);v656ok(v656call($p,'ebay_run_schedule_new_business_gap_revalidation',$after,$cov2,'public_verify')===true,'second_distinct_churn_revalidated');$a2=get_option($runKey,[]);v656ok(count((array)$a2['gapfill']['missing'])===305&&($a2['gapfill']['discovery_missing']??[])===[$required[6]],'second_churn_monotonic_delta');
$unknown=$after;$covU=['required'=>311,'covered'=>7,'missing'=>array_merge($current,['unknown_family']),'counts'=>[]];update_option($runKey,$unknown,false);v656call($p,'ebay_run_schedule_new_business_gap_revalidation',$unknown,$covU,'coverage_verify');$uf=get_option($runKey,[]);v656ok(($uf['status']??'')==='failed'&&($uf['error_code']??'')==='business_coverage_unknown_family','unknown_family_still_hard');

$render=new ReflectionMethod($p,'render_banner');$render->setAccessible(true);$banner=['mode'=>'image_link','url'=>'https://example.invalid/p','image_url'=>'https://example.invalid/x.jpg','title'=>'Test','button_text'=>'Bei eBay ansehen','description'=>'','price'=>'59.90','currency'=>'EUR','availability'=>'available','creative_type'=>'product','target'=>'_blank','subid_param'=>''];$ctx=['primary_slug'=>'reitstiefel','primary_name'=>'Reitstiefel'];$grp=['id'=>'v656'];
foreach(['category_product_1','category_product_2','category_product_3'] as $slot){$html=(string)$render->invoke($p,$banner,123,$ctx,$grp,$slot);v656ok(strpos($html,'data-ppar-category-product-image-fit="contain"')!==false&&strpos($html,'object-fit:contain!important')!==false&&strpos($html,'width:150px!important')!==false&&strpos($html,'height:150px!important')!==false,$slot.'_contain_150');}
$am=new ReflectionMethod($p,'article_plan_render_product_card_markup');$am->setAccessible(true);$ah=(string)$am->invoke($p,$banner,1,$ctx,$grp,'post_bottom_products');v656ok(strpos($ah,'ppar-article-product-link')!==false&&strpos($ah,'ppar-banner-')===false,'article_product_renderer_unchanged');

v656ok(v656call($p,'ebay_business_materialization_error_is_recoverable',new WP_Error('ebay_business_import_failed','x'))===true,'candidate_error_skippable');v656ok(v656call($p,'ebay_business_materialization_error_is_recoverable',new WP_Error('storage_unavailable','x'))===false,'storage_error_hard');

delete_option($runKey);delete_option($checkpointKey);delete_option(Pferdeportal_Affiliate_Router::OPTION_EBAY_EXTERNAL_TICK_RATE_LOCK);
echo "REAL_V656_ASSERTIONS={$GLOBALS['v656_a']} FAIL={$GLOBALS['v656_f']}\n";exit($GLOBALS['v656_f']?1:0);
