<?php
$root=getenv('PPAR_TEST_PLUGIN_DIR')?:''; if($root===''||!is_dir($root)){fwrite(STDERR,"PPAR_TEST_PLUGIN_DIR missing\n");exit(2);} 
$main=file_get_contents($root.'/pferdeportal-affiliate-router.php');$run=file_get_contents($root.'/includes/trait-ppar-ebay-run.php');$ebay=file_get_contents($root.'/includes/trait-ppar-ebay.php');$readme=file_get_contents($root.'/readme.txt');
$tests=0;$fails=0;function ok656($c,$n){global $tests,$fails;$tests++;if(!$c){$fails++;echo "FAIL $n\n";}else echo "PASS $n\n";}
function body656($src,$needle){$p=strpos($src,$needle);if($p===false)return '';$b=strpos($src,'{',$p);$d=0;for($i=$b,$l=strlen($src);$i<$l;$i++){if($src[$i]==='{')$d++;elseif($src[$i]==='}'&&--$d===0)return substr($src,$b+1,$i-$b-1);}return '';}
$handler=body656($run,'public function handle_ebay_external_tick');$url=body656($run,'private function ebay_external_tick_url');$admit=body656($run,'private function ebay_external_tick_admit');$register=body656($run,'public function register_ebay_external_tick_route');$worker=body656($run,'public function run_ebay_canonical_worker');$contract=body656($run,'private function ebay_run_business_safe_supply_gap_contract');$reval=body656($run,'private function ebay_run_schedule_new_business_gap_revalidation');$coverage=body656($run,'private function ebay_run_tick_coverage');$public=body656($run,'private function ebay_run_tick_public_verify');$recover=body656($ebay,'private function ebay_business_recovery_missing_concept_ids');
ok656(strpos($main,"const VERSION = '6.56.0';")!==false,'version_656');ok656(strpos($main,"const EBAY_RUNTIME_BUILD = '6.56.0-safe-gap-churn-revalidation-rootfix-20260827';")!==false,'runtime_build_656');
ok656(strpos($main,'OPTION_EBAY_EXTERNAL_TICK_RATE_LOCK')!==false,'rate_lock_constant');ok656(strpos($register,"'methods'=>'POST'")!==false,'heartbeat_post_only');ok656(strpos($register,"'permission_callback'=>'__return_true'")!==false,'public_trigger_only');ok656(strpos($url,'rest_url(')!==false&&strpos($url,'add_query_arg')===false&&strpos($url,"'key'")===false,'heartbeat_url_no_secret');ok656(strpos($run,'private function ebay_external_tick_key')===false,'secret_generator_removed');ok656(strpos($handler,'get_param')===false&&strpos($handler,'hash_equals')===false&&strpos($handler,'forbidden')===false,'handler_no_shared_secret');ok656(strpos($admit,'< 45')!==false&&strpos($admit,'add_option(')!==false,'durable_45s_gate');ok656(strpos($handler,"'status'=>'throttled'")!==false,'throttle_response');ok656(substr_count($handler,'run_ebay_canonical_worker()')===1,'one_package_per_tick');ok656(strpos($handler,'ebay_external_tick_due_operation')!==false,'due_operation_preserved');ok656(strpos($handler,"'restart_required'=>1")!==false,'failed_run_no_auto_restart');ok656(strpos($handler,"'run_uuid'")===false&&strpos($handler,"'error_code'")===false,'public_response_minimal');ok656(strpos($worker,'while(')===false&&strpos($worker,'for(')===false&&strpos($worker,'foreach(')===false,'worker_bounded');ok656(strpos($worker,'wp_schedule')===false&&strpos($worker,'spawn_cron')===false&&strpos($worker,'wp_remote_')===false,'worker_no_self_transport');
ok656(strpos($ebay,'kein zusätzlicher externer Account ist erforderlich')!==false,'ui_no_external_account');ok656(strpos($ebay,'Heartbeat-URL enthält keinen Geheimschlüssel')!==false,'ui_no_secret');ok656(strpos($ebay,'POST-Ticks')!==false,'ui_post_only');ok656(strpos($readme,'SAFE-GAP CHURN REVALIDATION ROOTFIX')!==false,'readme_v656');ok656(strpos($readme,'je 45 Sekunden')!==false,'readme_rate_gate');ok656(strpos($readme,'Kandidatbezogene Einzelfehler')!==false,'readme_skip_contract');
ok656(strpos($contract,"business_safe_gap_new_missing_family")!==false,'historic_new_missing_guard_retained');ok656(strpos($contract,"business_gapfill_public_invariant_failed")!==false,'selected_not_public_invariant_retained');ok656(strpos($contract,"business_safe_gap_scope_mismatch")!==false,'scope_mismatch_guard_retained');ok656(strpos($contract,"business_safe_gap_proof_missing")!==false,'proof_missing_guard_retained');
ok656(strpos($coverage,"ebay_run_schedule_new_business_gap_revalidation")!==false,'coverage_revalidation_before_contract');ok656(strpos($public,"ebay_run_schedule_new_business_gap_revalidation")!==false,'public_revalidation_before_promotion');ok656(strpos($reval,"business_safe_gap_dynamic_revalidation")!==false,'explicit_revalidation_state');ok656(strpos($reval,"\$run['phase_state']['discovery']=array()")!==false&&strpos($reval,"\$run['phase_state']['selection']=array()")!==false,'derived_tail_only_reset');ok656(strpos($reval,"count(\$expanded)>count(\$required)")!==false,'manifest_bound');ok656(strpos($recover,"gapfill']['discovery_missing")!==false,'delta_discovery');
echo "ASSERTIONS=$tests FAIL=$fails\n";exit($fails?1:0);
