<?php
$mode=getenv('GATE_MODE')?:'build_positive';
$uuid='d4fd17b4-f44a-4b89-8e12-live-observed';$cp='safe-live-checkpoint';
function gate_fail($m){fwrite(STDERR,"FAIL $m\n");exit(1);} function gate_pass($m){echo "PASS $m\n";}
$admin=get_user_by('login','admin');if(!$admin)gate_fail('admin_missing');wp_set_current_user($admin->ID);
add_filter('pre_http_request',function($pre,$args,$url){return array('headers'=>array(),'body'=>'','response'=>array('code'=>202,'message'=>'Accepted'),'cookies'=>array(),'filename'=>null);},10,3);
$checkpoint=array('schema'=>'1.0','status'=>'safe','checkpoint_id'=>$cp,'business_campaign_ids'=>array(501,502),'private_listing_ids'=>array(101,102));
$buildrun=array('schema'=>'1.0','build'=>'6.47.0-dynamic-business-rule-context-rootfix-20260821','run_uuid'=>$uuid,'status'=>'failed','phase'=>'failed','finished_at'=>2000,'progress_contract_version'=>'3.1','worker_transport'=>'admin_ajax','config_snapshot'=>array('seller_routes'=>array('private'=>1,'business'=>1),'settings'=>array()),'checkpoint_base_id'=>$cp,'checkpoint_id'=>$cp,'checkpoint_safe'=>1,'checkpoint_candidate'=>array('business_campaign_ids'=>array(999),'private_listing_ids'=>array(888)),'phase_state'=>array('selection'=>array('status'=>'complete'),'discovery'=>array('cursor'=>123)),'coverage'=>array('required'=>311,'covered'=>0),'gapfill'=>array('attempts'=>2,'missing'=>array('stale')),'private_public_revalidation'=>array('status'=>'complete'),'errors'=>array(array('code'=>'run_build_changed_restart_required','at'=>2000,'details'=>array('phase'=>'reconcile_local','build'=>'6.63.4-live-observed-gap-proof-recovery-rootfix-20260828','previous_build'=>'6.47.0-dynamic-business-rule-context-rootfix-20260821','checkpoint_id'=>$cp,'progress_contract_version'=>'3.1'))),'error_code'=>'run_build_changed_restart_required','error_message'=>'Der alte Lauf wurde sauber beendet. Ein neuer Lauf startet vom letzten sicheren Checkpoint.');
update_option(Pferdeportal_Affiliate_Router::OPTION_EBAY_PUBLIC_CHECKPOINT,$checkpoint,false);update_option(Pferdeportal_Affiliate_Router::OPTION_EBAY_RUN_STATE,$buildrun,false);
if($mode==='build_negative'){
 $r=get_option(Pferdeportal_Affiliate_Router::OPTION_EBAY_RUN_STATE,array());
 if(($r['status']??'')!=='failed'||($r['error_code']??'')!=='run_build_changed_restart_required'||($r['run_uuid']??'')!==$uuid)gate_fail('v6634_build_change_terminal_negative');gate_pass('v6634_build_change_terminal_negative');
 if(method_exists(Pferdeportal_Affiliate_Router::instance(),'maybe_recover_ebay_build_change_checkpoint_same_uuid_v6636'))gate_fail('v6634_should_not_have_v6636_recovery');gate_pass('v6634_no_v6636_recovery');
 global $wpdb;$raw=$wpdb->get_var($wpdb->prepare("SELECT option_value FROM {$wpdb->options} WHERE option_name=%s",Pferdeportal_Affiliate_Router::OPTION_EBAY_RUN_STATE));if(!$raw||strpos($raw,$uuid)===false)gate_fail('negative_mariadb_persisted');gate_pass('negative_mariadb_persisted');exit(0);
}
if(Pferdeportal_Affiliate_Router::VERSION!=='6.63.6')gate_fail('version_6636');gate_pass('version_6636');
$o=Pferdeportal_Affiliate_Router::instance();$o->maybe_recover_ebay_build_change_checkpoint_same_uuid_v6636();$r=get_option(Pferdeportal_Affiliate_Router::OPTION_EBAY_RUN_STATE,array());
if(($r['status']??'')!=='running'||($r['phase']??'')!=='reconcile_local')gate_fail('build_change_reopened');gate_pass('build_change_reopened');
if(($r['run_uuid']??'')!==$uuid)gate_fail('build_change_same_uuid');gate_pass('build_change_same_uuid');
if(($r['checkpoint_candidate']['business_campaign_ids']??array())!==array(501,502)||($r['checkpoint_candidate']['private_listing_ids']??array())!==array(101,102))gate_fail('checkpoint_candidate_safe_reset');gate_pass('checkpoint_candidate_safe_reset');
if(($r['resume_reason']??'')!=='same_uuid_safe_checkpoint_reentry')gate_fail('build_change_resume_reason');gate_pass('build_change_resume_reason');
$before=count((array)($r['recovery_history']??array()));$o->maybe_recover_ebay_build_change_checkpoint_same_uuid_v6636();$r2=get_option(Pferdeportal_Affiliate_Router::OPTION_EBAY_RUN_STATE,array());if(count((array)($r2['recovery_history']??array()))!==$before)gate_fail('build_change_idempotent');gate_pass('build_change_idempotent');
global $wpdb;$raw=$wpdb->get_var($wpdb->prepare("SELECT option_value FROM {$wpdb->options} WHERE option_name=%s",Pferdeportal_Affiliate_Router::OPTION_EBAY_RUN_STATE));if(!$raw||strpos($raw,$uuid)===false)gate_fail('v6636_real_mariadb_persisted');gate_pass('v6636_real_mariadb_persisted');
$uuid2='74b8372b-f481-493b-8485-1e98188ef02c';$proof=array('owner'=>'run:'.$uuid2,'business_target_concepts'=>array('concept-a'),'selected_concepts'=>array(),'created_at'=>1000);
$fresh=array('schema'=>'1.0','build'=>'6.63.4-live-observed-gap-proof-recovery-rootfix-20260828','run_uuid'=>$uuid2,'status'=>'failed','phase'=>'failed','finished_at'=>3000,'worker_transport'=>'external_tick','resume_reason'=>'private_public_revalidated','progress_seq'=>20,'progress_contract_version'=>'3.1','config_snapshot'=>array('seller_routes'=>array('private'=>1,'business'=>1),'settings'=>array()),'phase_state'=>array('discovery'=>array('status'=>'completed','cursor'=>3159),'selection'=>array('status'=>'complete','phase'=>'complete','prepare_private_scanned'=>545,'prepare_private_leaf_index'=>8)),'gapfill'=>array('attempts'=>2,'missing'=>array('concept-a'),'selection_proof'=>$proof),'checkpoint_candidate'=>array('business_campaign_ids'=>array(501,502),'private_listing_ids'=>array(101,102)),'private_public_revalidation'=>array('status'=>'complete','attempts'=>1,'completed_at'=>2900),'recovery_history'=>array(array('reason'=>'business_gap_proof_regeneration','error_code'=>'business_safe_gap_proof_missing','migration_key'=>'prior')),'errors'=>array(array('code'=>'private_public_gate_failed','at'=>3000,'details'=>array('phase'=>'public_verify','build'=>'6.63.4-live-observed-gap-proof-recovery-rootfix-20260828','invalid'=>array(101=>'source_stale'),'public'=>250))),'error_code'=>'private_public_gate_failed','error_message'=>'PRIVATE-Public-Gate ist fehlgeschlagen.');
update_option(Pferdeportal_Affiliate_Router::OPTION_EBAY_RUN_STATE,$fresh,false);$o->maybe_recover_ebay_private_public_freshness_v6635();$fr=get_option(Pferdeportal_Affiliate_Router::OPTION_EBAY_RUN_STATE,array());if(($fr['status']??'')!=='running'||($fr['phase']??'')!=='selection_prepare'||($fr['run_uuid']??'')!==$uuid2)gate_fail('v6635_freshness_regression_same_uuid');gate_pass('v6635_freshness_regression_same_uuid');
echo "REAL_DB_GATE_V6636_PASS\n";
