<?php

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

/**
 * Read-only bridge from a bound Product Comparison post to Affiliate.
 *
 * Productwissen/Comparison owns the fachliche exact product identity.
 * Affiliate owns offer, price, availability, seller and tracking.
 * No Affiliate table is read or written here.
 */
class UPC_Affiliate_Bridge {

    public static function register() {
        add_filter(
            'ppar_affiliate_exact_product_requirements',
            array( __CLASS__, 'exact_product_requirements' ),
            10,
            4
        );
    }

    public static function exact_product_requirements( $requirements, $post_id, $context = array(), $schema = '' ) {
        $requirements = is_array( $requirements ) ? $requirements : array();
        $post_id      = absint( $post_id );

        if ( $post_id <= 0 || ! upc_dependency_ready() ) {
            return $requirements;
        }

        $comparison_id = self::comparison_id_for_post( $post_id );
        if ( $comparison_id <= 0 ) {
            return $requirements;
        }

        $repository = upc_repository();
        if ( is_wp_error( $repository ) ) {
            return $requirements;
        }

        $bundle = $repository->get_comparison_bundle( $comparison_id );
        if ( is_wp_error( $bundle ) || empty( $bundle['items'] ) || ! is_array( $bundle['items'] ) ) {
            return $requirements;
        }

        foreach ( $bundle['items'] as $item ) {
            if ( ! is_array( $item ) || empty( $item['knowledge'] ) || ! is_array( $item['knowledge'] ) ) {
                continue;
            }

            $identifiers = self::exact_identifiers( $item['knowledge'] );
            if ( empty( $identifiers ) ) {
                // Fail closed: a comparison subject without a stable Affiliate-
                // exact identifier must not receive a fuzzy or SKU substitute.
                continue;
            }

            $subject_type = sanitize_key( (string) ( $item['subject_type'] ?? '' ) );
            $subject_id   = absint( $item['subject_id'] ?? 0 );
            if ( '' === $subject_type || $subject_id <= 0 ) {
                continue;
            }

            $requirements[] = array(
                'subject_id'  => $subject_type . ':' . $subject_id,
                'identifiers' => $identifiers,
                'position'    => max( 1, absint( $item['position'] ?? 1 ) ),
            );
        }

        return $requirements;
    }

    private static function comparison_id_for_post( $post_id ) {
        $comparison_id = absint( get_post_meta( $post_id, '_upc_comparison_id', true ) );
        if ( $comparison_id > 0 ) {
            return $comparison_id;
        }

        // Backward-safe bridge for drafts created before _upc_comparison_id
        // existed. The UID format is generated by UPC itself.
        $uid = trim( (string) get_post_meta( $post_id, '_upc_comparison_uid', true ) );
        if ( preg_match( '/^UPC-([0-9]+)$/', $uid, $match ) ) {
            return absint( $match[1] );
        }

        return 0;
    }

    private static function exact_identifiers( array $knowledge ) {
        $out = array();

        // Affiliate Exact Match is deliberately narrower than Productwissen.
        // MANUFACTURER_ARTICLE_NUMBER remains useful product knowledge but is
        // not an automatic commerce match key. This prevents merchant SKU /
        // manufacturer article-number confusion from producing substitutions.
        $allowed = array( 'GTIN', 'EAN', 'MPN' );

        foreach ( (array) ( $knowledge['identifiers'] ?? array() ) as $identifier ) {
            if ( ! is_array( $identifier ) ) {
                continue;
            }

            $type = strtoupper( sanitize_text_field(
                (string) ( $identifier['identifier_type'] ?? $identifier['type'] ?? '' )
            ) );
            $value = trim( sanitize_text_field(
                (string) ( $identifier['identifier_value'] ?? $identifier['value'] ?? '' )
            ) );

            if ( '' === $value || ! in_array( $type, $allowed, true ) ) {
                continue;
            }

            $key = $type . ':' . $value;
            $out[ $key ] = array(
                'type'  => $type,
                'value' => $value,
            );
        }

        return array_values( $out );
    }
}
